import { PlatformRaw, ContractRaw } from "../types";
export const platform: PlatformRaw = {
  id: "realms",
  name: "Realms",
  description:
    "Realms is a DAO governance platform that enables organizations to create proposals, vote, and manage treasuries using SPL Governance.",
  defiLlamaId: "spl-governance",
  links: {
    website: "https://app.realms.today/",
    discord: "https://discord.gg/6UZHcNJFr8",
    github: "https://github.com/Mythic-Project",
    documentation: "https://docs.realms.today/",
    twitter: "https://x.com/RealmsDAOs",
  },
  tags: ["dao", "tool", "dapp"],
};

export const contracts: ContractRaw[] = [
  { name: "VSR", address: "vsr2nfGVNHmSY8uxoBGqq8AQbwz3JwaEaHqGbsTPXqQ" },
  { name: "VSR", address: "GovER5Lthms3bLBqWub97yVrMmEogzX7xNjdXpPPCVZw" },
  { name: "VSR", address: "gUAedF544JeE6NYbQakQvribHykUNgaPJqcgf3UQVnY" },
  { name: "VSR", address: "GqTPL6qRf5aUuqscLh8Rg2HTxPUXfhhAXDptTLhp1t2J" },
  { name: "VSR", address: "DcG2PZTnj8s4Pnmp7xJswniCskckU5E6XsrKuyD7NYFK" },
  { name: "VSR", address: "4ruGZqLoPVKX27Qm91Qjsqt5AzCtLrhmjKT8ubwHiVZu" },
  { name: "VSR", address: "AEauWRrpn9Cs6GXujzdp1YhMmv2288kBt3SdEcPYEerr" },
  { name: "VSR", address: "AVoAYTs36yB5izAaBkxRG67wL1AMwG3vo41hKtUSb8is" },
  { name: "VSR", address: "G41fmJzd29v7Qmdi8ZyTBBYa98ghh3cwHBTexqCG1PQJ" },
  { name: "VSR", address: "GovHgfDPyQ1GwazJTDY2avSVY8GGcpmCapmmCsymRaGe" },
  { name: "VSR", address: "J9uWvULFL47gtCPvgR3oN7W357iehn5WF2Vn9MJvcSxz" },
  { name: "VSR", address: "JPGov2SBA6f7XSJF5R4Si5jEJekGiyrwP2m7gSEqLUs" },
  { name: "VSR", address: "5hAykmD4YGcQ7Am3N7nC9kyELq6CThAkU82nhNKDJiCy" },
  { name: "VSR", address: "gSF1T5PdLc2EutzwAyeExvdW27ySDtFp88ri5Aymah6" },
  { name: "VSR", address: "GmtpXy362L8cZfkRmTZMYunWVe8TyRjX5B7sodPZ63LJ" },
  { name: "VSR", address: "GMpXgTSJt2nJ7zjD1RwbT2QyPhKqD2MjAZuEaLsfPYLF" },
  { name: "VSR", address: "bqTjmeob6XTdfh12px2fZq4aJMpfSY1R1nHZ44VgVZD" },
  { name: "VSR", address: "Ghope52FuF6HU3AAhJuAAyS2fiqbVhkAotb7YprL5tdS" },
  { name: "VSR", address: "5sGZEdn32y8nHax7TxEyoHuPS3UXfPWtisgm8kqxat8H" },
  { name: "VSR", address: "smfjietFKFJ4Sbw1cqESBTpPhF4CwbMwN8kBEC1e5ui" },
  { name: "VSR", address: "GovMaiHfpVPw8BAM1mbdzgmSZYDw2tdP32J2fapoQoYs" },
  { name: "VSR", address: "GCockTxUjxuMdojHiABVZ5NKp6At8eTKDiizbPjiCo4m" },
  { name: "VSR", address: "HT19EcD68zn7NoCF79b2ucQF8XaMdowyPt5ccS6g1PUx" },
  { name: "VSR", address: "GRNPT8MPw3LYY6RdjsgKeFji5kMiG1fSxnxDjDBu4s73" },
  { name: "VSR", address: "ALLGnZikNaJQeN4KCAbDjZRSzvSefUdeTpk18yfizZvT" },
  { name: "VSR", address: "A7kmu2kUcnQwAVn8B4znQmGJeUrsJ1WEhYVMtmiBLkEr" },
  { name: "VSR", address: "MGovW65tDhMMcpEmsegpsdgvzb6zUwGsNjhXFxRAnjd" },
  { name: "VSR", address: "jdaoDN37BrVRvxuXSeyR7xE5Z9CAoQApexGrQJbnj6V" },
  { name: "VSR", address: "GMnke6kxYvqoAXgbFGnu84QzvNHoqqTnijWSXYYTFQbB" },
  { name: "VSR", address: "Di9ZVJeJrRZdQEWzAFYmfjukjR5dUQb7KMaDmv34rNJg" },
  { name: "VSR", address: "hgovkRU6Ghe1Qoyb54HdSLdqN7VtxaifBzRmh9jtd3S" },
  { name: "VSR", address: "dgov7NC8iaumWw3k8TkmLDybvZBCmd1qwxgLAGAsWxf" },
  { name: "VSR", address: "GovRp7uazvmYkQ7gqjdfjKFwr6pHDcYFWH3SP9DHzdtR" },
  { name: "VSR", address: "VoteMBhDCqGLRgYpp9o7DGyq81KNmwjXQRAHStjtJsS" },
  { name: "VSR", address: "4Q6WW2ouZ6V3iaNm56MTd5n2tnTm4C5fiH8miFHnAFHo" },
  { name: "VSR", address: "VotEn9AWwTFtJPJSMV5F9jsMY6QwWM5qn3XP9PATGW7" },
  { name: "VSR", address: "5sWzuuYkeWLBdAv3ULrBfqA51zF7Y4rnVzereboNDCPn" },
];
